# Application Details
spring.application.name=eureka-server
server.port = 8761

# Do not register itself
eureka.client.register-with-eureka = false
eureka.client.fetch-registry = false

# Disable self-preservation for local
eureka.server.enable-self-preservation = false
